package pl.peterwolf.cinewolf.montage.event;

public enum ReplayEventType {
    POSITION_CHANGE,
    HIGH_SPEED,
    ACCELERATION,
    DECELERATION,
    SHARP_TURN,
    ALTITUDE_GAIN,
    ALTITUDE_LOSS,
    COMBAT,
    DAMAGE,
    DEATH,
    VEHICLE_ENTER,
    VEHICLE_EXIT,
    VEHICLE_MOVEMENT,
    FLIGHT_START,
    FLIGHT,
    LANDING,
    BLOCK_PLACEMENT,
    BLOCK_DESTRUCTION,
    TREE_CUTTING,
    FARMING,
    MINING,
    EXPLORATION,
    PAUSE,
    REPLAY_MARKER
}
