org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.160.7+26.3
flashback_version=0.43.4
flashback_modrinth_id=h6FH7iAC

mod_version=2.0.34
maven_group=pl.peterwolf.cinewolf
archives_base_name=cinewolf-autodirector
